version: 2
jobs:
  build:
    docker:
      - image: stevenrbrandt/clangmi
    steps:
      - checkout
      - run: mkdir build
      - run: env CXX=clang++ LIBRARY_PATH=/usr/local/lib64  cmake  -S . -B build
      - run: cd build && env CXX=clang++ LIBRARY_PATH=/usr/local/lib64 make -j 2 VERBOSE=1
      - run: cd build && env CXX=clang++ LIBRARY_PATH=/usr/local/lib64 ctest
