version: 2
jobs:
  build:
    docker:
      - image: stevenrbrandt/clangmi
    steps:
      - checkout
      - run: mkdir build
      - run: cmake  -S . -B build
      - run: cd build && make -j 2
      - run: cd build && ctest
