version: 2
jobs:
  build:
    docker:
      - image: stevenrbrandt/clangmi
    steps:
      - checkout
      - run: mkdir build
      - run: env CXX=clang++ LD_LIBRARY_PATH=/usr/local/lib64  cmake  -S . -B build
      - run: cd build && env CXX=clang++ LD_LIBRARY_PATH=/usr/local/lib64 make -j 2
      - run: cd build && env CXX=clang++ LD_LIBRARY_PATH=/usr/local/lib64 ctest
